---
nameOverride: ""
fullnameOverride: ""

ingress:
  enabled: false
  className: ""
  annotations: {}
  hostname: "" # poker-planning.local
  services:
    frontendName: ""
    backendName: ""
  tls:
    enabled: false
    secretName: ""
