{{- if .Values.ingress.enabled -}}
{{- $fullName := include "poker-planning.fullname" . -}}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "poker-planning.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:    
    - hosts:      
        - {{ .Values.ingress.hostname }}          
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:          
          - path: /graphql
            pathType: Prefix            
            backend:              
              service:
                name: {{ .Values.ingress.services.backendName}}
                port:
                  number: 8000    
          - path: /
            pathType: ImplementationSpecific
            backend:            
              service:
                name: {{ .Values.ingress.services.frontendName }}
                port:
                  number: 80
{{- end }}