---
name: Frontend Push
on:
  push:
    branches:
      - main
    paths:
      - "client/**"

jobs:
  frontend_image:
    uses: ./.github/workflows/image.yaml
    with:
      image_name: "poker-planning-fe"
      directory: "./client"
