name: "Publish Helm Flux Chart"
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "chart/**"

permissions:
  contents: read
  packages: write

env:
  OCI_MANIFESTS_BASE_URL: "oci://ghcr.io/jontze/manifests"
  OCI_MANIFESTS_REPO: "oci://ghcr.io/jontze/manifests/poker-planning"
  OCI_MANIFESTS_PATH: "./chart/poker-planning"

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Helm Login
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io --username jontze --password-stdin
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: jontze
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup flux cli
        uses: fluxcd/flux2/action@main
      - name: Push Helm Manifests to OCI Image
        run: |
          export CHART_VERSION=$(helm show chart $OCI_MANIFESTS_PATH | yq e '.version' -)
          export CHART_NAME=$(helm show chart $OCI_MANIFESTS_PATH | yq e '.name' -)
          helm package $OCI_MANIFESTS_PATH
          helm push $CHART_NAME-$CHART_VERSION.tgz $OCI_MANIFESTS_BASE_URL          
          flux tag artifact $OCI_MANIFESTS_REPO:$CHART_VERSION \
            --tag latest \
            --tag $(git rev-parse --short HEAD)
